apiVersion: v1
kind: Pod
metadata:
    name: pod-02
    labels:
      app: segundo-pod
spec:
    containers:
        - name: container-pod-02
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 512Mi
              cpu: "1"