apiVersion: v1
kind: Pod
metadata:
    name: pod-01
    labels:
      app: primeiro-pod
spec:
    containers:
        - name: container-pod-01
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
             limits:
                memory: 512Mi
                cpu: "1"