apiVersion: v1
kind: ConfigMap
metadata:
  name: sistema-configmap
  labels:
    app: sistema-configmap
data:
  HOST_DB: svc-db-noticias:3306
  USER_DB: root
  PASS_DB: nmttpocos
  DATABASE_DB: empresa
